# Generated by Django 5.1.2 on 2024-11-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_contact_delete_customer_delete_menuitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact1',
        ),
    ]
